"use client";

import { useEffect, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import type { Laporan } from "./LaporanTable";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/shared/ui/dialog";
import { Button } from "@/components/shared/ui/button";
import { Input } from "@/components/shared/ui/input";
import { Label } from "@/components/shared/ui/label";

const FIELDS: { key: keyof Laporan; label: string }[] = [
    { key: "tahun", label: "Tahun" },
    { key: "pers_no", label: "Pers No" },
    { key: "nik", label: "NIK" },
    { key: "nama", label: "Nama" },
    { key: "jabatan", label: "Jabatan" },
    { key: "ou", label: "OU" },
    { key: "file", label: "File" },
    { key: "status_approved", label: "Status Approved" },
    { key: "site", label: "Site" },
    { key: "approved_by", label: "Approved By" },
    { key: "sign_loc", label: "Sign Loc" },
    { key: "kode_jabatan", label: "Kode Jabatan" },
    { key: "jabatan_lengkap", label: "Jabatan Lengkap" },
    { key: "dept_id", label: "Dept ID" },
    { key: "department", label: "Department" },
    { key: "div_id", label: "Div ID" },
    { key: "divisi", label: "Divisi" },
    { key: "direktorat_id", label: "Direktorat ID" },
    { key: "direktorat", label: "Direktorat" },
    { key: "work_contract_id", label: "Work Contract ID" },
    { key: "work_contract", label: "Work Contract" },
    { key: "updated_by", label: "Updated By" },
    { key: "generated_by", label: "Generated By" },
];

const EMPTY: Partial<Laporan> = {};

interface Props {
    open: boolean;
    onClose: () => void;
    editData: Laporan | null;
}

export default function LaporanFormModal({ open, onClose, editData }: Props) {
    const queryClient = useQueryClient();
    const [form, setForm] = useState<Partial<Laporan>>(EMPTY);
    const [error, setError] = useState("");

    useEffect(() => {
        setForm(editData ?? EMPTY);
        setError("");

        // Toggle navbar visibility
        if (open) {
            document.body.classList.add("modal-open-hide-navbar");
        } else {
            document.body.classList.remove("modal-open-hide-navbar");
        }

        // Cleanup in case component unmounts while modal is open
        return () => {
            document.body.classList.remove("modal-open-hide-navbar");
        };
    }, [editData, open]);

    const mutation = useMutation({
        mutationFn: async (data: Partial<Laporan>) => {
            const url = editData ? `/api/laporan/${editData.id}` : "/api/laporan";
            const method = editData ? "PUT" : "POST";
            const res = await fetch(url, {
                method,
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(data),
            });
            if (!res.ok) throw new Error("Gagal menyimpan data");
            return res.json();
        },
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["laporan"] });
            onClose();
        },
        onError: (e: Error) => setError(e.message),
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        mutation.mutate(form);
    };

    return (
        <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
            <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle style={{ color: "#2b4c3d" }}>
                        {editData ? "Edit Data Laporan" : "Tambah Data Laporan"}
                    </DialogTitle>
                </DialogHeader>
                {error && <div className="alert alert-danger text-sm">{error}</div>}
                <form onSubmit={handleSubmit}>
                    <div className="grid grid-cols-2 gap-x-4 gap-y-3">
                        {FIELDS.map(({ key, label }) => (
                            <div key={key} className="flex flex-col gap-1">
                                <Label htmlFor={key}>{label}</Label>
                                <Input
                                    id={key}
                                    value={(form[key] as string) ?? ""}
                                    onChange={(e) => setForm({ ...form, [key]: e.target.value })}
                                    placeholder={label}
                                />
                            </div>
                        ))}
                    </div>
                    <DialogFooter className="mt-4">
                        <Button type="button" variant="outline" onClick={onClose}>
                            Batal
                        </Button>
                        <Button
                            type="submit"
                            disabled={mutation.isPending}
                            style={{ backgroundColor: "#2b4c3d", color: "#fff", borderColor: "#2b4c3d" }}
                        >
                            {mutation.isPending ? "Menyimpan..." : "Simpan"}
                        </Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    );
}
